### ISSUE TITLE
Installation on Mac with M1

### ISSUE THREAD

**Issue by r0f1** [ome/conda-bioformats2raw#22]
Could you make a new build available of version 0.7.0 such that it is possible to install it under Mac?

Conda gives me the following messages:
```
conda search  -c ome bioformats2raw
Loading channels: done
# Name                       Version           Build  Channel             
bioformats2raw                 0.2.1               1  ome                 
bioformats2raw                 0.2.2               2  ome 
```
and
```
conda install -y -c ome 'bioformats2raw==0.7.0'
Channels:
 - ome
 - defaults
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - bioformats2raw==0.7.0

Current channels:

  - https://conda.anaconda.org/ome
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Downloading and installing [the latest zip file](https://github.com/glencoesoftware/bioformats2raw/releases/tag/v0.7.0) does not work either, because then I get a `Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Unable to load library 'blosc'` error that I cannot resolve.

Thank you.

**Comment by jni** [comment]
+1 from me... It's a bit weird that 0.2.1/2 are available for M1 but not later versions? Did some build script break that hasn't been fixed? 🤔 🙏 

Looking at the actions, issues, and PRs on this repo I'm not even sure whether this repo is the right place to report these... But glencoesoftware/bioformats2raw doesn't seem to do a conda build either... 🤔

**Comment by joshmoore** [comment]
> [r0f1](https://github.com/r0f1) commented [on Nov 3](https://github.com/ome/conda-bioformats2raw/issues/22#issue-1976566449)
> Downloading and installing [the latest zip file](https://github.com/glencoesoftware/bioformats2raw/releases/tag/v0.7.0) does not work either, because then I get a `Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Unable to load library 'blosc'` error that I cannot resolve.

I would assume this would happen with earlier versions as well.

https://github.com/ome/conda-bioformats2raw/blob/master/bioformats2raw/meta.yaml


> [jni](https://github.com/jni) commented [1 hour ago](https://github.com/ome/conda-bioformats2raw/issues/22#issuecomment-1844795658)
> +1 from me... It's a bit weird that 0.2.1/2 are available for M1 but not later versions? Did some build script break that hasn't been fixed? 🤔 🙏

I don't think so. (All actions passing, etc.) I think 0.2.x was before the split into the main build and the -libs one. I think this is a result of `-lib` having `  noarch: generic` and the main build not:

```
(base) ~ $mamba search -c ome bioformats2raw==0.7.0
...
Loading channels: done
No match found for: bioformats2raw==0.7.0. Search: *bioformats2raw*==0.7.0
# Name                       Version           Build  Channel
bioformats2raw-libs            0.7.0               0  ome
(base) ~ $mamba search -c ome bioformats2raw-libs
...
Loading channels: done
# Name                       Version           Build  Channel
bioformats2raw-libs            0.2.6               0  ome
bioformats2raw-libs            0.3.0               0  ome
bioformats2raw-libs            0.4.0               0  ome
bioformats2raw-libs            0.5.0               0  ome
bioformats2raw-libs            0.6.1               0  ome
bioformats2raw-libs            0.7.0               0  ome
(base) ~ $mamba search -c ome bioformats2raw-libs==0.7.0
...
Loading channels: done
# Name                       Version           Build  Channel
bioformats2raw-libs            0.7.0               0  ome
```

I'm not sure why that's the case though. I'm tempted to just try adding it unless someone the likes of @manics has an alternative.

**Comment by manics** [comment]
IIRC it's because windows and non-windows need different launch scripts. Python solves this problem by having console entrypoints which are coverted into a native launcher when the package is installed, but there's no equivalent for Java.

Unfortunately Conda doesn't have a way to say "noarch for all Unix based OS" so you'd need a build matrix of {windows,osx,linux} x {amd,arm} even though all non-windows packages would be identical.

Alternatively you could maybe bundle the Windows and Unix launch scripts in the same noarch launcher package, but I can't remember if there's any other differences.

**Comment by joshmoore** [comment]
Thanks, @manics. So ultimately the problem is that there's not a conda arm builder attached here... Hmmm... Tempted to workaround this by just pushing my local builds until builders are offered.

**Comment by manics** [comment]
I've no idea whether this would work and it's certainty not recommended.... but since there's no difference in the launch scripts for amd/arm perhaps you could unzip the Conda package, edit the metadata, and zip it back up under a new name?
